class ExceptionMessage {
  static const String apiExceptionMessage = 'API 요청 중 문제가 발생했습니다';
  static const String networkExceptionMessage = '네트워크 연결 실패';
  static const String unexpectedFetchUserExceptionMessage = '예기치 않은 오류로 사용자 데이터를 가져오는 데 실패했습니다';
  static const String databaseRepoFetchExceptionMessage = '저장소 데이터를 가져오는 중 오류가 발생했습니다';
  static const String databaseCacheRepoExceptionMessage = '저장소 캐싱 중 오류가 발생했습니다';
  static const String databaseClearRepoExceptionMessage = '저장소 캐시를 지우는 중 오류가 발생했습니다';
  static const String failedToFetchRepositories = '저장소 데이터를 가져오는 중 문제가 발생했습니다';
  static const String failedToLoadRepositories = '저장소 로드 실패';
  static const String failedToFetchCachedUsers = '캐시된 사용자 데이터를 가져오는 중 문제가 발생했습니다';
}
